FORMAT: 1A
HOST: https://example.com/wp-json/erp/v1/accounting

# WP ERP REST API

# Accounting API
<!-- include(includes/accounting/customers.apib) -->
<!-- include(includes/accounting/vendors.apib) -->
<!-- include(includes/accounting/employees.apib) -->
<!-- include(includes/accounting/people.apib) -->
<!-- include(includes/accounting/charts_ledgers.apib) -->
<!-- include(includes/accounting/accounts_transfers.apib) -->
<!-- include(includes/accounting/company.apib) -->
<!-- include(includes/accounting/currencies.apib) -->
<!-- include(includes/accounting/opening_balances.apib) -->
<!-- include(includes/accounting/closing_balance.apib) -->
<!-- include(includes/accounting/products.apib) -->
<!-- include(includes/accounting/product_cats.apib) -->
<!-- include(includes/accounting/tax_rates.apib) -->
<!-- include(includes/accounting/tax_rate_lines.apib) -->
<!-- include(includes/accounting/tax_records.apib) -->
<!-- include(includes/accounting/tax_agencies.apib) -->
<!-- include(includes/accounting/tax_cats.apib) -->
<!-- include(includes/accounting/tax_rate_names.apib) -->
<!-- include(includes/accounting/invoices.apib) -->
<!-- include(includes/accounting/rec_payments.apib) -->
<!-- include(includes/accounting/expenses.apib) -->
<!-- include(includes/accounting/bills.apib) -->
<!-- include(includes/accounting/pay_bills.apib) -->
<!-- include(includes/accounting/purchases.apib) -->
<!-- include(includes/accounting/pay_purchases.apib) -->
<!-- include(includes/accounting/journals.apib) -->
<!-- include(includes/accounting/transactions.apib) -->
<!-- include(includes/accounting/reports.apib) -->

# CRM API

# HRM API
