# Group Tax Records


## Manage All Tax Records [taxes/tax-records]

### Retrieve All Tax Records [GET]

+ Response 200 (application/json)
    + Body

            [
                {
                    "id": 1,
                    "voucher_no": "15",
                    "agency_id": "Arizona Revenue Department",
                    "trn_date": "2020-03-29",
                    "particulars": "Invoice created with voucher no 15",
                    "amount": "5.00",
                    "trn_by": "1",
                    "ledger_id": "Cash",
                    "voucher_type": "debit",
                    "created_at": "2020-03-29",
                    "namespace": "erp/v1",
                    "rest_base": "accounting/v1/taxes",
                    "_links": {
                        "self": {
                            "href": "https://example.com/wp-json/erp/v1/accounting/v1/taxes/1"
                        },
                        "collection": {
                            "href": "https://example.com/wp-json/erp/v1/accounting/v1/taxes"
                        }
                    }
                }
            ]


## Manage Single Tax Record [taxes/tax-records/{id}]

+ Parameters
    + id (string) - id of the tax_rate in the form of an string

### Retrieve A SIngle Tax Record [GET]

+ Response 200 (application/json)
    + Body

            {
                "id": 1,
                "voucher_no": "15",
                "agency_id": "Arizona Revenue Department",
                "trn_date": "2020-03-29",
                "particulars": "Invoice created with voucher no 15",
                "amount": "5.00",
                "trn_by": "1",
                "ledger_id": "Cash",
                "voucher_type": "debit",
                "created_at": "2020-03-29",
                "namespace": "erp/v1",
                "rest_base": "accounting/v1/taxes",
                "_links": {
                    "self": {
                        "href": "https://example.com/wp-json/erp/v1/accounting/v1/taxes/1"
                    },
                    "collection": {
                        "href": "https://example.com/wp-json/erp/v1/accounting/v1/taxes"
                    }
                }
            }

## Manage All Tax Records [taxes/tax-records]

### Retrieve All Tax Records [GET]

+ Response 200 (application/json)
    + Body

            [
                {
                    "id": 1,
                    "voucher_no": "15",
                    "agency_id": "Arizona Revenue Department",
                    "trn_date": "2020-03-29",
                    "particulars": "Invoice created with voucher no 15",
                    "amount": "5.00",
                    "trn_by": "1",
                    "ledger_id": "Cash",
                    "voucher_type": "debit",
                    "created_at": "2020-03-29",
                    "namespace": "erp/v1",
                    "rest_base": "accounting/v1/taxes",
                    "_links": {
                        "self": {
                            "href": "https://example.com/wp-json/erp/v1/accounting/v1/taxes/1"
                        },
                        "collection": {
                            "href": "https://example.com/wp-json/erp/v1/accounting/v1/taxes"
                        }
                    }
                }
            ]


## Pay against Tax Records [taxes/pay-tax]

### Pay against a Tax Record [POST]

    Model

    {
        "agency_id": 1,
        "trn_date": "2020-03-29",
        "trn_by": "1",
        "ledger_id": "7",
        "particulars": "",
        "voucher_type": "debit",
        "amount": 5
    }


+ Response 200 (application/json)
    + Body

            {
                "id": 1,
                "voucher_no": {
                    "id": "1",
                    "voucher_no": "15",
                    "particulars": "Invoice created with voucher no 15",
                    "amount": "5.00",
                    "trn_date": "2020-03-29",
                    "voucher_type": "debit",
                    "trn_by": "1",
                    "agency_id": "1",
                    "ledger_id": "7",
                    "created_at": "2020-03-29"
                },
                "agency_id": "Arizona Revenue Department",
                "trn_date": "2020-03-29",
                "particulars": "",
                "amount": 5,
                "trn_by": "1",
                "ledger_id": "Cash",
                "voucher_type": "debit",
                "created_at": null,
                "namespace": "erp/v1",
                "rest_base": "accounting/v1/taxes",
                "_links": {
                    "self": {
                        "href": "https://example.com/wp-json/erp/v1/accounting/v1/taxes/1"
                    },
                    "collection": {
                        "href": "https://example.com/wp-json/erp/v1/accounting/v1/taxes"
                    }
                }
            }
